#!/bin/bash
#  rctodosync v0.2 Share tasks with multiple users using todo.txt
#  Copyright (C) 2021 Angel. uGeek
#  ugeekpodcast@gmail.com
#
#
VERSION=v0.3
#
#



if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "h" ] || [ "$1" = "" ]
then

    echo "
---------------------------------------------------------------------------------                                                           
rctodosync      [opción]           Descripción
---------------------------------------------------------------------------------      
rctodosync      archivo_config     Sincroniza según el archivo de configuración
rctodosync      e  archivo_config  Editar archivo de configuración  
rctodosync      --help, h,...      Ayuda

rctodosync $VERSION
"
	exit
	fi


mkdir -p ~/.config/rctodosync


if [ -f ~/.config/rctodosync/editor ];
then
    source ~/.config/rctodosync/editor
else
    echo -en "¿Que editor de texto quieres utilizar para configurar rctodosync?: " ; read edit
    echo "EDITOR='$edit'" >  ~/.config/rctodosync/editor
    source ~/.config/rctodosync/editor
    exit
    fi            


if [ "$1" = "e" ]
then
    if [ -f ~/.config/rctodosync/$2 ];
    then
        echo ""
	else	
	    echo -en "No has indicado ningún archivo de configuración o no existe. ¿Quieres crearlo?: " ; read RESPUESTA
	    if [ "$RESPUESTA" = "SI" ] || [ "$RESPUESTA" = "S" ] || [ "$RESPUESTA" = "si" ] || [ "$RESPUESTA" = "s" ] || [ "$RESPUESTA" = "y" ] || [ "$RESPUESTA" = "yes" ]
            then
            $EDITOR ~/.config/rctodosync/$2
            clear
            fi
    exit
    fi
    fi


if [ "$1" = "e" ]
then
    $EDITOR ~/.config/rctodosync/$2
    exit
    fi  

source ~/.config/rctodosync/$1

chmod a+x ~/.config/rctodosync/*


$HOME/.config/rctodosync/notification "rctodosync: Iniciando sincronización de la sesión $1" > /dev/null 2>&1

echo "rctodo $VERSION. sincronizando 2 todo.txt 
       
        Intervalo de actualización $TIEMPO_ACTUALIZACION
        
        Archivo 1 : $SERVIDOR1       
        Archivo 2 : $SERVIDOR2 
"



TODOTXT1=$(rclone cat $SERVIDOR1/todo.txt)
DONETXT1=$(rclone cat $SERVIDOR1/done.txt)
TODOTXT2=$(rclone cat $SERVIDOR2/todo.txt)
DONETXT2=$(rclone cat $SERVIDOR2/done.txt)

# Filtramos para sincronizar
SYNCFILE=$(echo -e "$(echo "$TODOTXT1" | grep "$WORD")\n$(echo "$TODOTXT2" | grep "$WORD")" | sort | uniq)
SYNCFILEDONE=$(echo -e "$(echo "$DONETXT1" | grep "$WORD")\n$(echo "$DONETXT2" | grep "$WORD")" | sort | uniq)


echo "Tareas con la palabra $WORD"
echo "----------------------------------------"
echo "$SYNCFILE"
echo "----------------------------------------"
echo ""

echo -e "$(echo "$TODOTXT1" | grep -v "$WORD")\n$(echo "$SYNCFILE")"     | rclone rcat $SERVIDOR1/todo.txt
echo -e "$(echo "$DONETXT1" | grep -v "$WORD")\n$(echo "$SYNCFILEDONE")" | rclone rcat $SERVIDOR1/done.txt
echo -e "$(echo "$TODOTXT2" | grep -v "$WORD")\n$(echo "$SYNCFILE")"     | rclone rcat $SERVIDOR2/todo.txt
echo -e "$(echo "$DONETXT2" | grep -v "$WORD")\n$(echo "$SYNCFILEDONE")" | rclone rcat $SERVIDOR2/done.txt


while :
do
    
    echo -e "$(date +'%Y-%m-%d  %T')      update cada $TIEMPO_ACTUALIZACION"
 
    # Listamos tareas
    TODOTXT1=$(rclone cat $SERVIDOR1/todo.txt)    
    SYNCFILE1=$(echo -e "$(echo "$TODOTXT1" | grep "$WORD")")
    
    if [ "$SYNCFILE" != "$SYNCFILE1" ]; then
	echo ""
	echo "$(date +'%Y-%m-%d  %T')      Nueva entrada en Servidor 1. Sincronizando todo.txt"
	echo ""
	echo -e "$(echo "$TODOTXT1" | grep -v "$WORD")\n$(echo "$SYNCFILE1")" | rclone rcat $SERVIDOR1/todo.txt
	echo -e "$(echo "$TODOTXT2" | grep -v "$WORD")\n$(echo "$SYNCFILE1")" | rclone rcat $SERVIDOR2/todo.txt
	# done
        DONETXT1=$(rclone cat $SERVIDOR1/done.txt)
        DONETXT2=$(rclone cat $SERVIDOR2/done.txt)	
	SYNCFILEDONE=$(echo -e "$(echo "$DONETXT1" | grep "$WORD")\n$(echo "$DONETXT2" | grep "$WORD")" | sort | uniq)
	echo -e "$(echo "$DONETXT1" | grep -v "$WORD")\n$(echo "$SYNCFILEDONE")" | rclone rcat $SERVIDOR1/done.txt
        SYNCFILE=$(echo -e "$SYNCFILE1")
	$HOME/.config/rctodosync/notification "rctodosync: archivo todo.txt modificado en el Servidor 1 . Sesión $1" > /dev/null 2>&1
    fi
    
    TODOTXT2=$(rclone cat $SERVIDOR2/todo.txt)
    SYNCFILE2=$(echo -e "$(echo "$TODOTXT2" | grep "$WORD")")
    
    if [ "$SYNCFILE" != "$SYNCFILE2" ]; then
	echo ""
	echo "$(date +'%Y-%m-%d  %T')      Nueva entrada en Servidor 2. Sincronizando todo.txt"
	echo ""
	echo -e "$(echo "$TODOTXT2" | grep -v "$WORD")\n$(echo "$SYNCFILE2")" | rclone rcat $SERVIDOR2/todo.txt
	echo -e "$(echo "$TODOTXT1" | grep -v "$WORD")\n$(echo "$SYNCFILE2")" | rclone rcat $SERVIDOR1/todo.txt
	# done
        DONETXT1=$(rclone cat $SERVIDOR1/done.txt)
        DONETXT2=$(rclone cat $SERVIDOR2/done.txt)	
	SYNCFILEDONE=$(echo -e "$(echo "$DONETXT1" | grep "$WORD")\n$(echo "$DONETXT2" | grep "$WORD")" | sort | uniq)
	echo -e "$(echo "$DONETXT2" | grep -v "$WORD")\n$(echo "$SYNCFILEDONE")" | rclone rcat $SERVIDOR2/done.txt
        SYNCFILE=$(echo -e "$(echo "$TODOTXT1" | grep "$WORD")\n$(echo "$TODOTXT2" | grep "$WORD")" | sort | uniq)
	$HOME/.config/rctodosync/notification "rctodosync: archivo todo.txt modificado en el Servidor 2 . Sesión $1" > /dev/null 2>&1
    fi
    sleep $TIEMPO_ACTUALIZACION
done

